# Generated by Django 6.0.7 on 2026-07-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_details', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('allotted_time', models.DecimalField(decimal_places=2, help_text='Allotted time in hours', max_digits=6)),
                ('task_status', models.CharField(choices=[('not_started', 'Assigned / Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rework_needed', 'Rework Needed'), ('resubmitted', 'Resubmitted'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='not_started', max_length=20)),
                ('total_time_taken', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all closed TimerSession durations, in hours', max_digits=6)),
                ('remaining_or_over_time', models.DecimalField(decimal_places=2, default=0, help_text='allotted_time - total_time_taken. Negative = over time.', max_digits=6)),
                ('task_sheet_link', models.TextField(blank=True, help_text='Stored as-is, no URL validation')),
                ('employee_remarks', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('quality_of_task', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement'), ('rework_needed', 'Rework Needed'), ('rejected', 'Rejected')], max_length=25)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('rework_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_assigned', to='accounts.admin')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='accounts.employee')),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
            },
        ),
    ]
