# Generated by Django 6.0.7 on 2026-07-31 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allotted_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allotted time in hours', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='accounts.employee'),
        ),
    ]
