# Generated by Django 6.0.7 on 2026-07-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0002_alter_task_allotted_time_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_rework_session', models.BooleanField(default=False, help_text='True if this session was opened after a Rework Needed decision.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timer_sessions', to='accounts.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.task')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
