# Generated by Django 6.0.7 on 2026-08-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0003_timersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_before_hold',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Task Created'), ('assigned', 'Assigned / Reassigned'), ('started', 'Timer Started'), ('paused', 'Timer Paused'), ('resumed', 'Timer Resumed'), ('submitted', 'Submitted'), ('review_started', 'Review Started'), ('approved', 'Approved'), ('rework_requested', 'Rework Requested'), ('hold', 'Put On Hold'), ('released_hold', 'Hold Released'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('correction_requested', 'Time Correction Requested'), ('correction_decided', 'Time Correction Decided')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('actor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('original_end_time', models.DateTimeField()),
                ('requested_end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='accounts.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='tasks.timersession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
