# Generated by Django 6.0.7 on 2026-08-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0004_task_status_before_hold_activitylog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by_employee',
            field=models.ForeignKey(blank=True, help_text='Set when a TL creates the task instead of an Admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created_as_tl', to='accounts.employee'),
        ),
    ]
