# Generated by Django 6.0.7 on 2026-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
