# Generated by Django 6.0.7 on 2026-08-13 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_is_active'),
        ('tasks', '0007_alter_taskmaster_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='generated_for_date',
            field=models.DateField(blank=True, help_text='Which calendar day this occurrence belongs to. Only set for recurring-generated tasks.', null=True),
        ),
        migrations.CreateModel(
            name='RecurringTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_details', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('allotted_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_created', to='accounts.admin')),
                ('assigned_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_created_as_tl', to='accounts.employee')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_task_definitions', to='accounts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.recurringtaskdefinition'),
        ),
    ]
