# Generated by Django 6.0.7 on 2026-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_generated_for_date_recurringtaskdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtaskdefinition',
            name='exclude_sundays',
            field=models.BooleanField(default=False),
        ),
    ]
