# Generated by Django 6.0.7 on 2026-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_recurringtaskdefinition_exclude_sundays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtaskdefinition',
            name='exclude_sundays',
        ),
        migrations.AddField(
            model_name='recurringtaskdefinition',
            name='weekdays',
            field=models.JSONField(default=list, help_text='Python weekday ints this task should run on: Mon=0 ... Sun=6'),
        ),
    ]
