# Generated by Django 6.0.7 on 2026-08-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_employee_id'),
        ('tasks', '0010_remove_recurringtaskdefinition_exclude_sundays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed_as_tl', to='accounts.employee'),
        ),
    ]
