# Generated by Django 6.0.7 on 2026-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_employee_id'),
        ('tasks', '0011_task_reviewed_by_admin_task_reviewed_by_employee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_source__isnull', False)), fields=('recurring_source', 'generated_for_date'), name='one_task_per_recurring_def_per_day'),
        ),
    ]
