# Generated by Django 6.0.7 on 2026-08-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_one_task_per_recurring_def_per_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='one_task_per_recurring_def_per_day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewed_by_admin',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewed_by_employee',
        ),
    ]
